### ISSUE TITLE
Testing Firebase Authentication Integration

### ISSUE THREAD

**Issue by harshbhxtia** [harshbhatia66/project-mobi#24]
**Description:**
We need to test the integration of Firebase authentication between our frontend (React Native) and backend (Django). Currently, we're encountering an authorization error and a specific database issue when verifying the Firebase token. The error log is as follows:

```
Unauthorized: /api/test-token/
[26/Jan/2024 05:33:47] "POST /api/test-token/ HTTP/1.1" 401 130
Error verifying Firebase token: (1062, "Duplicate entry '' for key 'mobi_app_userprofile.firebase_uid'")
Unauthorized: /api/test-token/
[26/Jan/2024 05:33:50] "POST /api/test-token/ HTTP/1.1" 401 130
```

**Tasks:**
- [ ] Investigate and debug the `401 Unauthorized` error on the `/api/test-token/` endpoint.
- [ ] Resolve the `Duplicate entry '' for key 'mobi_app_userprofile.firebase_uid'` error in the Django backend.
- [ ] Ensure that the Firebase token is correctly sent from the frontend and received in the backend.
- [ ] Verify that the Firebase token is correctly decoded and validated in the backend.
- [ ] Test the entire flow of Firebase authentication from the frontend to the backend to ensure seamless integration.
- [ ] Document any findings and fixes to prevent similar issues in the future.

**Acceptance Criteria:**
- The Firebase token sent from the frontend is correctly verified in the Django backend.
- The `401 Unauthorized` and `Duplicate entry` errors are resolved.
- Firebase authentication integration is confirmed to be working correctly through successful testing.
